; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AA573EC4-6F00-49D4-B107-0834A5BC7836}
AppName=Node Defense
AppVersion=b1.2.3
;AppVerName=Node Defense b1.2.3
AppPublisher=Siege Studios
AppPublisherURL=https://kevinwyso.github.io/Node-Defense
AppSupportURL=https://kevinwyso.github.io/Node-Defense
AppUpdatesURL=https://kevinwyso.github.io/Node-Defense
DefaultDirName={pf}\Node Defense
DisableProgramGroupPage=yes
OutputBaseFilename=Node Defense Setup b1.2.3
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Filed\Documents\Unity Projects w Git\Node Defense\Node-Defense\Builds\Testing Builds\Beta v1.2.3.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Filed\Documents\Unity Projects w Git\Node Defense\Node-Defense\Builds\Testing Builds\Beta v1.2.3 Data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Node Defense"; Filename: "{app}\Beta v1.2.3.exe"
Name: "{commondesktop}\Node Defense"; Filename: "{app}\Beta v1.2.3.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Beta v1.2.3.exe"; Description: "{cm:LaunchProgram,Node Defense}"; Flags: nowait postinstall skipifsilent

